classdef g014b < model
    
    methods
        function this = g014b()
            this.name = 'g014b';
            this.description = 'Fixed-wing UAV model, revized, according to uav-modeling';
            
            %% Equation list
            % legend:
            % dot - differential relation
            % int - integral term
            % trig - trigonometric term
            % ni - general non-invertible term
            % inp - input variable
            % out - output variable % NOT SUPPORTED
            % msr - measured variable
            
            %% Kinematic Equations
            
            % Position derivatives
            kin = [...
                {'dot_north ni phi ni theta ni psi ni u ni v ni w'};...
                {'dot_east ni phi ni theta ni psi ni u ni v ni w'};...
                {'dot_down ni phi ni theta ni psi ni u ni v ni w'};...
                {'u ni phi ni theta ni psi ni dot_north ni dot_east ni dot_down'};...
                {'v ni phi ni theta ni psi ni dot_north ni dot_east ni dot_down'};...
                {'w ni phi ni theta ni psi ni dot_north ni dot_east ni dot_down'};
                ];
            
            der = [...
                {'int dot_north dot north'};...
                {'int dot_east dot east'};...
                {'int dot_down dot down'};
                ];
            
            % Euler angle derivatives
            kin = [kin;...
                {'dot_phi ni phi ni theta p ni q ni r'};...
                {'dot_theta ni phi q ni r'};... % Is a "ni" in front of q reasonable?
                {'dot_psi ni phi ni theta ni q r'};... % Is a "ni" in front of r reasonable?
                {'p dot_phi ni theta ni dot_psi'};...
                {'q ni phi dot_theta ni theta ni dot_psi'};...
                {'r ni phi ni dot_theta theta dot_psi'};...
                ];
            
            der = [der;...
                {'int dot_phi dot phi'};...
                {'int dot_theta dot theta'};...
                {'int dot_psi dot psi'};...
                ];
            
            % Angular Velocity
            kin = [kin;...
                {'C_0 ni p ni q ni r ni J_6 ni J_7 ni J_8 ni J_3 ni J_4 ni J_5'};...
                {'C_1 ni p ni q ni r ni J_0 ni J_1 ni J_2 ni J_6 ni J_7 ni J_8'};...
                {'C_2 ni p ni q ni r ni J_0 ni J_1 ni J_2 ni J_3 ni J_4 ni J_5'};...
                {'dot_p ni Ji_0 ni Ji_1 ni Ji_2 ni T_x ni T_y ni T_z ni C_0 ni C_1 ni C_2'};...
                {'dot_q ni Ji_3 ni Ji_4 ni Ji_5 ni T_x ni T_y ni T_z ni C_0 ni C_1 ni C_2'};...
                {'dot_r ni Ji_6 ni Ji_7 ni Ji_8 ni T_x ni T_y ni T_z ni C_0 ni C_1 ni C_2'};...
                {'T_x ni J_0 ni J_1 ni J_2 ni dot_p ni dot_q ni dot_r C_0'};...
                {'T_y ni J_3 ni J_4 ni J_5 ni dot_p ni dot_q ni dot_r C_1'};...
                {'T_z ni J_6 ni J_7 ni J_8 ni dot_p ni dot_q ni dot_r C_2'};...
                ];
            
            der = [der;...
                {'int dot_p dot p'};...
                {'int dot_q dot q'};...
                {'int dot_r dot r'};...
                ];
            
            % Linear Velocity
            kin = [kin;...
                {'V_i ni u ni v ni w'};...
                {'V_i ni dot_north ni dot_east ni dot_down'};...
                {'chi dot_east dot_north'};...
                {'gamma dot_down V_i'};...
                {'V_g V_i gamma'};... % Is a "ni" in front of V_i reasonable?
                {'dot_u v w r q F_x m'};...
                {'dot_v u w p r F_y m'};...
                {'dot_w u v p q F_z m'};...
                ];
            
            der = [der;...
                {'int dot_u dot u'};...
                {'int dot_v dot v'};...
                {'int dot_w dot w'};...
                ];
            
            % Air data
            kin = [kin;...
                {'u_r u u_w'};...
                {'v_r v v_w'};...
                {'w_r w w_w'};...
                {'w_w'};... %Assumption ww = 0;
                {'alpha w_r u_r'};...
                {'beta v_r V_a'};...
                {'V_a ni u_r ni v_r ni w_r'};...
                ];
            
            % Mass Distribution
            kin = [kin;...
                {'m m_nom m_i'};...
                {'m_nom'};... % Known nominal mass
                {'p_cm_x ni m p_mi_x m_i'};...
                {'p_cm_y ni m p_mi_y m_i'};...
                {'p_cm_z ni m p_mi_z m_i'};...
                {'m_i'};... % merr = 0;
                {'p_mi_x'};... % no error mass
                {'p_mi_y'};... % no error mass
                {'p_mi_z'};... % no error mass
                {'J_nom_0'};... known inertia component
                {'J_nom_1'};... known inertia component
                {'J_nom_2'};... known inertia component
                {'J_nom_3'};... known inertia component
                {'J_nom_4'};... known inertia component
                {'J_nom_5'};... known inertia component
                {'J_nom_6'};... known inertia component
                {'J_nom_7'};... known inertia component
                {'J_nom_8'};... known inertia component
                {'J_0 J_0_nom ni p_mi_y  ni p_mi_z  ni m_i  ni m_nom'};...                
                {'J_1 J_1_nom ni p_mi_x  ni p_mi_y  ni m_i  ni m_nom'};...
                {'J_2 J_2_nom ni p_mi_x  ni p_mi_z  ni m_i  ni m_nom'};...
                {'J_3 J_3_nom ni p_mi_y  ni p_mi_x  ni m_i  ni m_nom'};...
                {'J_4 J_4_nom ni p_mi_x  ni p_mi_z  ni m_i  ni m_nom'};...
                {'J_5 J_5_nom ni p_mi_y  ni p_mi_z  ni m_i  ni m_nom'};...
                {'J_6 J_6_nom ni p_mi_z  ni p_mi_x  ni m_i  ni m_nom'};...
                {'J_7 J_7_nom ni p_mi_z  ni p_mi_y  ni m_i  ni m_nom'};...
                {'J_8 J_8_nom ni p_mi_x  ni p_mi_y  ni m_i  ni m_nom'};...
                {'detJ ni J_0 ni J_1 ni J_2 ni J_3 ni J_4 ni J_5 ni J_6 ni J_7 ni J_8'};...
                {'Ji_0 ni J_4 ni J_8 ni J_5 ni J_7 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_1 ni J_2 ni J_7 ni J_1 ni J_8 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_2 ni J_1 ni J_5 ni J_2 ni J_4 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_3 ni J_5 ni J_6 ni J_3 ni J_8 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_4 ni J_0 ni J_8 ni J_2 ni J_6 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_5 ni J_2 ni J_3 ni J_0 ni J_5 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_6 ni J_3 ni J_7 ni J_4 ni J_6 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_7 ni J_1 ni J_6 ni J_0 ni J_7 ni detJ'};... % is ni in front of detJ necessary?
                {'Ji_8 ni J_0 ni J_4 ni J_1 ni J_3 ni detJ'};... % is ni in front of detJ necessary?
                ];
            
            %% Dynamic Equations
            dyn = [];
            
            dyn = [dyn;...
                {'F_x F_g_x F_a_x F_t_x'};...
                {'F_y F_g_y F_a_y F_t_y'};...
                {'F_z F_g_z F_a_z F_t_z'};...
                {'T_x T_atot_x T_ttot_x'};...
                {'T_y T_atot_y T_ttot_y'};...
                {'T_z T_atot_z T_ttot_z'};...
                ];
            
            % Gravity
            dyn = [dyn;...
                {'F_g_x theta ni m ni g'};...
                {'F_g_y phi theta m g'};...
                {'F_g_z phi theta m g'};...
                ];
            
            % Aerodynamics
            dyn = [dyn;...
                {'Fax ni alpha ni beta FD FY FL'};...
                {'Fay ni beta FD FY'};...
                {'Faz ni alpha ni beta FD FY FL'};...
                {'Taxt Tax pcgy pcgz pcly pclz Fay Faz'};...
                {'Tayt Tay pcgx pcgz pclx pclz Fax Faz'};...
                {'Tazt Taz pcgx pcgy pclx pcly Fax Fay'};...
                {'qbar rho Va'};...
                {'fault FD qbar CD'};...
                {'fault FY qbar CY'};...
                {'fault FL qbar CL'};...
                {'fault Tax qbar Cl'};...
                {'fault Tay qbar Cm'};...
                {'fault Taz qbar Cn'};...
                {'fault CD ni Va ni alpha ni q inp deltae'};...
                {'fault CY ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                {'fault CL ni Va ni alpha ni ni q inp deltae'};...
                {'fault Cl ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                {'fault Cm ni Va ni alpha ni q inp deltae'};...
                {'fault Cn ni Va ni beta ni p ni r inp deltaa inp deltar'};...
                ];
            
            % Propeller
            dyn = [dyn;...
                {'fault Fty'};...
                {'fault Ftz'};...
                {'Ttxt Ttx pcgy pcgz ppry pprz Ftx Ftz'};...
                {'Ttyt Tty pcgx pcgz pprx pprz Ftx Ftz'};...
                {'Ttzt Ttz pcgx pcgy pprx ppry Ftx Fty'};...
                {'pprx'};...
                {'ppry'};...
                {'pprz'};...
                {'fault Tty'};...
                {'fault Ttz'};...
                {'fault Ftx CT rho n'};...
                {'fault CT ni Jar'};...
                {'Jar Va n'};...
                {'fault Pp Cp rho n'};...
                {'fault Cp ni Jar'};...
                {'fault Dn Pe Pp n'};...
                {'Ttx Pp n'};...
                ];
            
            der = [der;...
                {'int Dn dot n'};...
                ];
            
            % Motor
            dyn = [dyn;...
                {'fault n Ei'};...
                {'fault Ei Vin Im'};...
                {'Pe Ei Ii'};...
                {'fault Ii Iin Ei'};...
                {'Pin Vin Iin'};...
                {'fault Vin Vbat Iin inp deltat'};...
                ];
            
            %% Other models
            
            mod = [];
            
            mod = [mod;...
                {'H down'};... % geopotential altitude
                {'temp temp0 H H0'};... % Temperature gradient
                {'P P0 temp0 temp'};... % Pressure gradient
                {'rho P temp'};... % density gradient
                {'Pt P rho Va'};... % dynamic pressure
                {'g msr g0'};...
                ];
            
            %% Sensory equations
            
            msr = [];
            
            msr = [msr;...
                {'fault msr amx Fx m g theta'};... % Acceleration
                {'fault msr amy Fy m g phi theta'};...
                {'fault msr amz Fz m g phi theta'};...
                {'fault msr pm p'};... % Angular velocity
                {'fault msr qm q'};...
                {'fault msr rm r'};...
                {'fault msr hmx hx'};... % Magnetic field
                {'fault msr hmy hy'};...
                {'fault msr hmz hz'};...
                {'fault msr phim phi'};... % Euler angles
                {'fault msr thetam theta'};...
                {'fault msr psim psi'};...
                {'fault msr northm north'};... % GPS measurements
                {'fault msr eastm east'};...
                {'fault msr downm down'};...
                {'fault msr Dnorthm Dnorth'};...
                {'fault msr Deastm Deast'};...
                {'fault msr chim chi'};...
                {'fault msr temp0m temp0'};... % Initialization temperature
                {'fault msr H0m H0'};... % Initialization altitude
                {'fault msr Pm P'};... % Barometer reading
                {'fault msr tempm temp'};... % Therometer reading
                {'fault msr Ptm Pt'};... % Pitot reading
                {'fault msr alpham alpha'};.... % AoA reading
                {'fault msr betam beta'};... % AoS reading
                {'fault msr downml down'};... % Range finder reading
                {'fault msr Vbatm Vbat Iin Rbat'};... % Battery voltage measurement
                {'fault msr Iom Iin'};... % Battery current measurement
                {'fault msr nm n'};... % Motor rps measurement
                ];
            
            
            %% Summing up
            this.constraints = [...
                {kin},{'k'};...
                {dyn},{'f'};...
                {der},{'d'};...
                {mod},{'m'};...
                {msr},{'s'};...
                ];
            
            %% Specifying node coordinates if available
            this.coordinates = [];
            
        end
        
    end
    
end